// Generated by build.rs from ch32-metapac metadata.
// Available constants:
//   FLASH_WRITE_SIZE: usize - write granularity in bytes
//   FLASH_ERASE_SIZE: usize - erase granularity in bytes
//   APP_BASE: u32         - base address of app section
//   APP_SIZE: usize       - app section size in bytes
//   META_BASE: u32        - base address of boot meta struct
//   RAM_BASE: u32         - base address of RAM
include!(concat!(env!("OUT_DIR"), "/constants.rs"));

pub(crate) const APP_PTR: *const u32 = APP_BASE as *const u32;
