// Generated by build.rs from ch32-metapac metadata.
include!(concat!(env!("OUT_DIR"), "/constants.rs"));

pub(crate) const BOOT_REQUEST_PTR: *mut u32 = RAM_BASE as *mut u32;
pub(crate) const BOOT_REQUEST_MAGIC: u32 = 0xB007_CAFE;

#[cfg(feature = "bootloader")]
pub(crate) const APP_PTR: *const u32 = APP_BASE as *const u32;
